apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-carto
  labels:
    app: dynatrace-carto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dynatrace-carto
  template:
    metadata:
      labels:
        app: dynatrace-carto
      annotations:
        networking.k8s.io/network-policy: dynatrace-carto-network-policy
    spec:
      imagePullSecrets:
      - name: project-registries
      containers:
      - name: dynatrace-carto
        image: dynatrace-carto:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: dynatrace-carto-secrets
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        terminationGracePeriodSeconds: 60 