apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dynatrace-carto-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: dynatrace-carto.example.com  # À remplacer par votre domaine
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: dynatrace-carto
            port:
              number: 80 