apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dynatrace-cartography-network-policy
spec:
  podSelector:
    matchLabels:
      app: dynatrace-cartography
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53 