apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dynatrace-carto-network-policy
spec:
  podSelector:
    matchLabels:
      app: dynatrace-carto
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    ports:
    - protocol: TCP
      port: 443
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53