apiVersion: v1
kind: Service
metadata:
  name: dynatrace-carto
spec:
  selector:
    app: dynatrace-carto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800 